config/routes.rb
Rails.application.routes.draw do
  resources :transactions
  root 'home#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/transaction.rb
class AccountFormatValidator < ActiveModel::Validator
  # Could've also used splits
  def validate(record)
    # Validate if IBAN of bank_account is correct
   if record.bank_account.length  == 22 && record.contra_account.length  == 22
    i = 0
    while i<21
      if (i==2 || i==3) || i>=8
          if !numeric?(record.bank_account[i]);
            record.errors.add :bank_account, ': A valid IBAN has two numbers after the first two letters! IBAN format: two letters, two digits, four letters, 14 digits.'
          end
      else 
          if !letter?(record.bank_account[i]);
            record.errors.add :bank_account, ': A valid IBAN starts with two letters! IBAN format: two letters, two digits, four letters, 14 digits. '
          end
      end
      i+=1 
    end 
    # Validate if IBAN of contra_account is correct
    i = 0
    while i<21
      if (i==2 || i==3) || i>=8
          if !numeric?(record.contra_account[i]);
            record.errors.add :contra_account, ': A valid IBAN has two numbers after the first two letters! IBAN format: two letters, two digits, four letters, 14 digits.'
          end
      else 
          if !letter?(record.contra_account[i]);
            record.errors.add :contra_account, ': A valid IBAN starts with two letters! IBAN format: two letters, two digits, four letters, 14 digits. '
          end
      end
      i+=1 
    end 
   end
    
    # Validate if currency is USD/EUR or €/$
    currency_Valid = false
    case record.currency 
    when "USD", "EUR"
        currency_Valid = true
        
    end
    if !currency_Valid
        record.errors.add :currency, ': Provide a valid currency! Either EUR, USD'
    end
    # Validate if date is today or future
    if  Date.today>record.transaction_date
        record.errors.add :transaction_date, ': The transaction date should be today or in the future'
    end
    # Validate if funding type is either DEBIT or CREDIT
    funding_Type_Valid = false
    case record.funding_type 
    when "DEBIT", "CREDIT"
        funding_Type_Valid = true
        
    end
    if !funding_Type_Valid
        record.errors.add :funding_type, ': Provide a valid funding type! Either DEBIT or CREDIT'
    end
  end
end

def letter?(str)
    true if str[/[a-zA-Z]+/]  == str rescue false 
end

def numeric?(str)
    true if Integer(str) rescue false
end

class Transaction < ApplicationRecord
  # All entries except desc should be filled in:
  validates :currency, :bank_account, :contra_account, :contra_account_owner, :amount, :funding_type,
            presence: true
  # Only numbers:
  validates :amount, numericality: true

  # Specific lenght
  validates :bank_account, length: { is: 22 }
  validates :contra_account, length: { is: 22 }

  validates_with AccountFormatValidator
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def transactions

  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[ show edit update destroy ]

  # GET /transactions or /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1 or /transactions/1.json
  def show
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit
  end

  # POST /transactions or /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)

    respond_to do |format|
      if @transaction.save
        format.html { redirect_to @transaction, notice: "Transaction was successfully created." }
        format.json { render :show, status: :created, location: @transaction }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /transactions/1 or /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: "Transaction was successfully updated." }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1 or /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: "Transaction was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_transaction
      @transaction = Transaction.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def transaction_params
      params.require(:transaction).permit(:transaction_date, :bank_account, :contra_account, :contra_account_owner, :amount, :currency, :funding_type, :desc)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/home/_navbar.html.erb
<div class="navbar">
  <div class="nav_items">
    <%= link_to 'Dashboard', root_path %>
    <%= link_to 'Add transaction', new_transaction_path %>
    <%= link_to 'Transaction history', transactions_path %>
  </div>
</div>

app/views/home/index.html.erb
<div class="dashboard_container">
  <div>
    <h1>Creating new transactions the easy way</h1>
    <p>This simple online banking application will let you create new transactions and view earlier created transactions. Before a transaction can be saved it will be checked if it adheres to all specifications for a transaction</p>
    <h3>Mandatory fields for a transaction</h3>
    <ul>
      <li>
        Date (either current or future date)
      </li>
      <li>
        Bank account (must be valid IBAN)
      </li>
      <li>
        Contra account (must be valid IBAN)
      </li>
      <li>
        Contra account owner
      </li>
      <li>
        Amount (must be a number)
      </li>
      <li>
        Currency (EUR or USD)
      </li>
      <li>
        Funding type (CREDIT or DEBIT)
      </li>
    </ul>
  </div>
</div>

app/views/home/transactions.html.erb
<h1>Transaction history</h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OnlineBanking</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", media: "all", 'data-turbolinks-track': "reload" %>
    <%= javascript_pack_tag "application", 'data-turbolinks-track': "reload" %>
  </head>
  <body>
    <%= render "home/navbar" %>
    <div>
      <%= yield %>
    </div>
  </body>
</html>

app/views/transactions/_form.html.erb
<%= form_with(model: transaction) do |form| %>
  <% if transaction.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(transaction.errors.count, "error") %> prohibited this transaction from being saved:</h2>
      <ul>
        <% transaction.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= form.label :transaction_date %>
    <div><%= form.date_select :transaction_date %></div>
  </div>
  <div class="field">
    <%= form.label :bank_account %>
    <div><%= form.text_field :bank_account %></div>
  </div>
  <div class="field">
    <%= form.label :contra_account %>
    <div><%= form.text_field :contra_account %></div>
  </div>
  <div class="field">
    <%= form.label :contra_account_owner %>
    <div><%= form.text_field :contra_account_owner %></div>
  </div>
  <div class="field">
    <%= form.label :amount %>
    <div> <%= form.text_field :amount %></div>
  </div>
  <div class="field">
    <%= form.label :currency %>
    <div> <%= form.text_field :currency %></div>
  </div>
  <div class="field">
    <%= form.label :funding_type %>
    <div><%= form.text_field :funding_type %></div>
  </div>
  <div class="field">
    <%= form.label :desc %>
    <div><%= form.text_field :desc %></div>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/transactions/edit.html.erb
<div class="transaction_form">
  <div class="container">
    <h1>Editing Transaction</h1>
    <%= render 'form', transaction: @transaction %>
    <%= link_to 'Show', @transaction %> |
    <%= link_to 'Back', transactions_path %></div>
</div>

app/views/transactions/index.html.erb
<div class="transaction_history">
  <p id="notice"><%= notice %></p>
  <h1>Transactions</h1>
  <table>
    <thead>
      <tr>
        <th class="wide">Transaction date</th>
        <th>Bank account</th>
        <th>Contra account</th>
        <th class="wide">Contra account owner</th>
        <th>Amount</th>
        <th>Currency</th>
        <th class="wide">Funding type</th>
        <th>Desc</th>
        <th colspan="3"></th>
      </tr>
    </thead>
    <tbody>
      <% @transactions.each do |transaction| %>
        <tr>
          <td><%= transaction.transaction_date %></td>
          <td><%= transaction.bank_account %></td>
          <td><%= transaction.contra_account %></td>
          <td><%= transaction.contra_account_owner %></td>
          <td><%= transaction.amount %></td>
          <td><%= transaction.currency %></td>
          <td><%= transaction.funding_type %></td>
          <td><%= transaction.desc %></td>
          <td><%= link_to 'Show', transaction %></td>
          <td><%= link_to 'Edit', edit_transaction_path(transaction) %></td>
          <td><%= link_to 'Destroy', transaction, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <%= link_to 'New Transaction', new_transaction_path%></div>

app/views/transactions/new.html.erb
<div class="transaction_form">
  <div class="container">
    <h1>New Transaction</h1>
    <%= render 'form', transaction: @transaction %>
    <%= link_to 'Back', transactions_path %></div>
</div>

app/views/transactions/show.html.erb
<div class="show">
  <div>
    <p id="notice"><%= notice %></p>
    <p>
      <strong>Transaction date:</strong>
      <%= @transaction.transaction_date %>
    </p>
    <p>
      <strong>Bank account:</strong>
      <%= @transaction.bank_account %>
    </p>
    <p>
      <strong>Contra account:</strong>
      <%= @transaction.contra_account %>
    </p>
    <p>
      <strong>Contra account owner:</strong>
      <%= @transaction.contra_account_owner %>
    </p>
    <p>
      <strong>Amount:</strong>
      <%= @transaction.amount %>
    </p>
    <p>
      <strong>Currency:</strong>
      <%= @transaction.currency %>
    </p>
    <p>
      <strong>Funding type:</strong>
      <%= @transaction.funding_type %>
    </p>
    <p>
      <strong>Desc:</strong>
      <%= @transaction.desc %>
    </p>
    <%= link_to 'Edit', edit_transaction_path(@transaction) %> |
    <%= link_to 'Back', transactions_path %></div>
</div>